# Generated by Django 2.2.2 on 2019-07-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190702_2101'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dailyrecord',
            constraint=models.UniqueConstraint(fields=('habit', 'date'), name='habit_date'),
        ),
    ]
